### ISSUE TITLE
HAPI removes Bundle.entry.resource.meta information

### ISSUE THREAD

**Issue by seanmcilvenna** [hapifhir/hapi-fhir#1731]
**Describe the bug**
When storing a Bundle resource either via POST or PUT, HAPI is removing Bundle.entry.resource.meta information.

**To Reproduce**
POST/PUT a Bundle that has Bundle.entry.resource.meta.
When retrieving the Bundle, the information in Bundle.entry.resource.meta is gone.

**Expected behavior**
All information in the Bundle should be preserved.

**Environment (please complete the following information):**
 - HAPI FHIR Version 4.2
 - OS: Linux
 - Browser Postman

**Comment by jamesagnew** [comment]
We have dedicated tables/columns for storing Resource.meta information, which is why we strip the meta contents from the body of what we are storing. That apparently has the side effect that we also strip the meta from embedded resources in the Bundle (which we shouldn't do) and it also means we filter out extensions in Resource.meta when it's stored.

I propose we resolve this by refining the exclusion filter that we use when we serialize resources to the DB. Instead of exluding `*.meta` it should be a targeted list:

* `[resourcename].meta.tag`
* `[resourcename].meta.security`
* `[resourcename].meta.profile`
* `[resourcename].meta.lastUpdated`
* `[resourcename].meta.versionId`

**Comment by jamesagnew** [comment]
I don't know for sure that this is the right fix, but it is a good starting point. This fix should cover both scenarios I describe.
