### ISSUE TITLE
SQL exception when using $expunge due to hfj_res_link entries

### ISSUE THREAD

**Issue by seanmcilvenna** [hapifhir/hapi-fhir#2015]
**Describe the bug**
I'm not sure if this bug is related to $expunge, or incorrectly deleting entries in `hfj_res_link` when a resource is deleted...

Server is configured to _not_ enforce referential integrity.
Deleted a StructureDefinition, which is referenced by AuditEvent resources via the "entity" search parameter.
When I run $expunge on the deleted StructureDefinition, it fails with the following exception:

```
ERROR o.h.e.jdbc.spi.SqlExceptionHelper [SqlExceptionHelper.java:142] Cannot delete or update a parent row: a foreign key constraint fails (`hapi4-db`.`hfj_res_link`, CONSTRAINT `FK_RESLINK_TARGET` FOREIGN KEY (`TARGET_RESOURCE_ID`) REFERENCES `hfj_resource` (`RES_ID`))
```

In this example, each of the AuditEvent resources need to be deleted _before running $expunge_ so that the entries in the `hfj_res_link` table are removed.

**To Reproduce**
1. Create a StructureDefinition
2. Create an AuditEvent that references the StructureDefinition
3. DELETE the StructureDefinition
4. $expunge the StructureDefinition

**Expected behavior**
$expunge should run without exception

**Environment (please complete the following information):**
 - HAPI FHIR Version 4.2
 - OS: Ubuntu Server, Windows 10 client
 - Browser Postman

**Comment by jamesagnew** [comment]
This appears to be a legitimate issue. 

Expunge doesn't remove inbound references from things that it is expunging, and it generally shouldn't since those references are properties of other resources than the ones being expunged. Normally a delete or cascade-delete should be performed first.

In this case though, if ref-integrity is disabled it is reasonable for expunge to force-delete the incoming references. That would add a bit of processing time but I think that's a reasonable tradeoff.

**Comment by jamesagnew** [comment]
After reviewing.. This turns out to already be solved. It was legitimate but was dealt with as a part of the expunge refactoring late last year.

Passing test added: https://github.com/hapifhir/hapi-fhir/commit/72026811e67ed0806d61ccc426437d05c8b0031a
