### ISSUE TITLE
Conditional Create in transaction Bundle not working for Observations when the identifier is used

### ISSUE THREAD

**Issue by brianreinhold** [hapifhir/hapi-fhir#2653]
NOTE: Before filing a ticket, please see the following URL:
https://github.com/hapifhir/hapi-fhir/wiki/Getting-Help

**Describe the bug**
If I do an upload of a transaction bundle with conditional creates twice, I expect that the second upload will return a status of 200 OK. That is true for the Device and Patient resources, but not for the Observation. All the conditional create options for the  'ifNoneExist' use the identifier.

**To Reproduce**
Upload the attached transaction bundle on the R4 version.
[TransactionBundle.txt](https://github.com/hapifhir/hapi-fhir/files/6469181/TransactionBundle.txt)
Upload the same bundle again.

**Expected behavior**
Only one of the resources on the second upload should result in a 201 create, but all the Observations are recreated. One can then go to the server and do a search on the very identifier used and you will get multiple duplicates of the Observations.
For example the identifier here:

"ifNoneExist":"identifier=B4E782FFFF4B4A10-VL-testing-Ren-urn:oid:2.2.2.333-150364-41.34-6048-20210427133226.444+0800"

There is another problem. The response I get after the upload (though a 200) does NOT contain the standard Bundle response for a transaction. That is a second bug.

**Environment (please complete the following information):**
 - HAPI FHIR Version R4
 - OS: [e.g. iOS] Windows 10

**Comment by jamesagnew** [comment]
Hi Brian!

I spent some time staring at this pondering how it could possibly not work, given that conditional creates are really basic and used all the time. Eventually it hit me: The issue is this part of the ID: `444+0800`

It's completely fine to have a plus symbol in an identifier, but of course when you create the `IfNoneExist` expression, it's a URL and it needs to be URL encoded. And wouldnt you know it, a `+` translates to a space character when we unescape the URL.

So the solution is to escape the + in your URL. 

I am gonna leave this ticket open though- I think it would be reasonable for Smile to be lenient here and not unescape plus symbols. I can't imagine a situation where someone would actually want a space character in their URL and intentionally put a plus symbol there to represent it. Or at least it seems way less likely than the opposite...

**Comment by brianreinhold** [comment]
James! Thanks for that. I would have NEVER guessed that a '+' sign would need to be escaped. I will give it a try and see if it works

Well I tried 
B4E782FFFF4B4A10-VL-testing-Ren-urn:oid:2.2.2.333-150364-41.34-6048-20210427133226.444%2B0800
on
B4E782FFFF4B4A10-VL-testing-Ren-urn:oid:2.2.2.333-150364-41.34-6048-20210427133226.444+0800
and it didn't work. As far as I see, %2B is the proper escaping of the URL. What are you expecting?

This is what I got

"div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><h1>Operation Outcome</h1><table border=\"0\"><tr><td style=\"font-weight: bold;\">ERROR</td><td>[]</td><td><pre>Failed to CREATE resource with match URL &quot;identifier=B4E782FFFF4B4A10-VL-testing-Ren-urn:oid:2.2.2.333-67996-71-544-20210427133226.444%2B0800&quot; because this search matched 14 resources

I tried $2B as well and \\+ as different ways to escape. None worked, only one reported an error (%2B), the others I get 201 created.

**Comment by jamesagnew** [comment]
FWIW feel free to delete the previously uploaded resources. It should work fine after that.
