### ISSUE TITLE
DateAndList datatype doesn't support datetimestamp without milisec with zoneID(2015-02-07T13:28:17+00:00) 

### ISSUE THREAD

**Issue by AjeetYadav07** [hapifhir/hapi-fhir#6043]
Sending 2015-02-07T13:28:17+00:00(when not including milisec) for the last_updated parameter in our questionnaire API (using hapi library DateAndList type) might cause hapi to return an error. It seems DateAndList might not expect time zones without milisecond.

{
"resourceType": "OperationOutcome",
"issue": [
{
"severity": "error",
"code": "processing",
"diagnostics": "HAPI-1883: Invalid date/time format: "2015-02-07T13:28:17 00:00": Expected character '.' at index 19 but found "
}
]
}

**Expected behavior**
it should accept the zone offset without milisecond precision as well.

**Screenshots**
![image](https://github.com/hapifhir/hapi-fhir/assets/68940876/79c9149d-2f53-46e9-903e-e7f6b6257300)

**Environment (please complete the following information):**
 - 20.0.0
 - OS: mac
 - Browser : postman

**Comment by rajankapadia** [comment]
As per HL7 FHIR specification given in to below URL "dateTime" data type should support Format : **YYYY-MM-DDThh:mm:ss+zz:zz**  . We had seen current HAPI FHIR implementation is always expecting millsec if we pass +zz:zz ( timezone) component as a input. 

https://www.hl7.org/fhir/R4/datatypes.html#dateTime

**Comment by rajankapadia** [comment]
@jamesagnew any more update on this issue?

**Comment by jamesagnew** [comment]
You need to properly escape the `+` character, it's being correctly treated as a space by the server. I'm surprised that whatever testing UI you're using in that screenshot (postman presumably?) isn't doing that for you automatically but it clearly isn't since the error shows a space character where the + was.

Replace the `+` with `%2B` and I'd assume it should work.
