### ISSUE TITLE
Different behavior for encodeResourceToString after updating to hapi fhir 7.6.0 #1827

### ISSUE THREAD

**Issue by lasred** [hapifhir/hapi-fhir#6504]
After upgrading to hapi fhir version 7.6.0 we have noticed the encodeResourceToString method treats the references differently that the previous version we had(7.4.5).
For example, before calling the method we have a provenance with an organization as an agent, and the organization contains a null id. After the method is called the id value is replaced with a UUID.
The resource:
{ "resourceType": "Provenance", "id": "TypeId34adae3b8-3b99-4675-b664-e09fc605f59c", "contained": [ { "resourceType": "Organization", "id": "9f48dcaf-5f0e-4c1b-8784-ff429d76e76a", "identifier": [ { "system": "SYS1", "value": "IDT1" } ], "name": "orgName" } ], "target": [ { "reference": "AllergyIntolerance/TypeId3" } ], "recorded": "2024-11-22T16:15:59.532-05:00", "agent": [ { "type": { "coding": [ { "system": "http://terminology.hl7.org/CodeSystem/provenance-participant-type", "code": "author", "display": "Author" } ], "text": "author" }, "who": { "reference": "#9f48dcaf-5f0e-4c1b-8784-ff429d76e76a" } } ] }
The organization id did not have this value "9f48dcaf-5f0e-4c1b-8784-ff429d76e76a" before entering the method.

Why was the id of the organization replaced with an UUID? Thank you!

**Comment by jamesagnew** [comment]
This sounds like the change caused by https://github.com/hapifhir/hapi-fhir/issues/6403 - We now auto generate contained IDs using UUIDs instead of sequential numeric IDs. Your Organization resource is contained within the Provenance, so it needs an ID in order to be valid and HAPI will assign one if it doesn't already have one.

(Note- please use our Google Group to ask questions about HAPI FHIR. Details here: https://github.com/hapifhir/hapi-fhir/wiki/Getting-Help )
